### ISSUE TITLE
Conversation break markers still not always getting parsed correctly

### ISSUE THREAD

**Issue by JamesCowling** [a16z-infra/ai-town#95] opened 2023-08-15 16:44 UTC
<img width="273" alt="Screenshot 2023-08-15 at 9 42 18 AM" src="https://github.com/a16z-infra/ai-town/assets/8008486/6517ee44-394d-45f0-ad78-441ad22a7825">

**Comment by vakila** [comment] 2023-08-16 14:17
I'm going to look into this per conversation with @ianmacartney 
 
 Seems this is also a duplicate of #82

**Comment by ianmacartney** [comment] 2023-08-16 21:56
#101 is a stopgap

**Closed by ianmacartney** 2023-08-16 21:56 UTC
Labels: bug
